# Generated by Django 4.0.5 on 2022-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=300)),
                ('height', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=45)),
                ('lifespan', models.CharField(max_length=15)),
                ('intelligence', models.CharField(max_length=15)),
                ('activity', models.CharField(max_length=15)),
                ('coat', models.CharField(max_length=15)),
                ('vocalness', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
