# Generated by Django 4.0.5 on 2022-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.TextField(max_length=500),
        ),
    ]
