# Generated by Django 4.0.5 on 2022-06-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='created_at',
        ),
    ]
