# Generated by Django 4.0.4 on 2022-06-03 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='preview',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
