# Generated by Django 4.0.4 on 2022-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_cat_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='info',
            field=models.TextField(max_length=1500),
        ),
    ]
